# Generated by Django 3.0 on 2020-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=50)),
                ('adminEmail', models.CharField(max_length=50)),
                ('adminPhone', models.IntegerField()),
                ('adminUser', models.CharField(max_length=50)),
                ('adminPass', models.CharField(max_length=20)),
                ('adminRole', models.CharField(max_length=40)),
                ('adminStatus', models.IntegerField()),
                ('adminDT', models.DateTimeField(auto_now=True)),
                ('adminPerms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
