# Generated by Django 3.0 on 2020-01-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionIn', models.CharField(max_length=15)),
                ('sessionOut', models.CharField(max_length=15)),
                ('sessionStat', models.IntegerField()),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Details')),
            ],
        ),
    ]
