# Generated by Django 3.0 on 2020-01-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=50)),
                ('adminEmail', models.CharField(max_length=50)),
                ('adminPhone', models.IntegerField()),
                ('adminUser', models.CharField(max_length=50)),
                ('adminPass', models.CharField(max_length=20)),
                ('adminRole', models.CharField(max_length=40)),
                ('adminStatus', models.IntegerField()),
                ('adminDT', models.DateTimeField(auto_now=True)),
                ('adminPerms', models.IntegerField()),
            ],
        ),
    ]
