# Generated by Django 3.0 on 2020-01-29 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserDetails'),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
