# Generated by Django 3.0 on 2020-01-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200129_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='adminRef',
            field=models.CharField(default='Master', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='adminPass',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='adminPhone',
            field=models.CharField(max_length=11),
        ),
    ]
